### ISSUE TITLE
Sentry's `User` class conflicts with application's `User` class

### ISSUE THREAD

**Issue by wouterw** [getsentry/sentry-swift#31]
Can't use `SentryClient.shared?.user` because I have a class named `User` in my app.

**Comment by joshdholtz** [comment]
@wouterw How are you using/installing this client? It should be namespaced out with the module name (if using as a dynamic framework) if you have a conflicting class name - `SentrySwift.User`. I have not come across this myself yet but I will take a look into this today for ya ✊

**Comment by wouterw** [comment]
@joshdholtz Sorry for the noise, referencing `SentrySwift.User` explicitly works. Thanks for the quick reply! 👍

**Comment by joshdholtz** [comment]
@wouterw No problem, man 😊 Glad that worked! Have fun Sentry-ing and let me know if you run into any other issues or have any suggestions 👍

**Comment by carole-lavillonniere** [comment]
I have the same issue using Sentry-Swift installed through Carthage.
The problem occurs even without using your class `SentrySwift.User`, but simply because it is defined in your framework, so prefixing it is not a solution for me. Here is the compilation error I get:
```
Error:(2788, 1) duplicate interface definition for class 'User'
```

**Comment by joshdholtz** [comment]
@carole-lavillonniere How are you installing the library? Are you using either CocoaPods or Carthage?

**Comment by carole-lavillonniere** [comment]
I am using Carthage as mentioned.

```
github "getsentry/sentry-swift" == 0.3.3
```

**Comment by joshdholtz** [comment]
@carole-lavillonniere Sorry, my bad! Just woke up like 5 minutes ago 😇  I will take a look at once I made my cup of coffee ☕

**Comment by joshdholtz** [comment]
@carole-lavillonniere Does your `User` class happen to be an Objective-C class by any chance? 😊

**Comment by carole-lavillonniere** [comment]
It is a Swift class but it does inherit from NSObject.

**Comment by joshdholtz** [comment]
Hmmm... Fairly certain that error is an Objective-C error so that does make more sense. I was able to duplicate the error in an a Objective-C project but have not in a Swift project yet. Will work on a fix though 👍

**Comment by joshdholtz** [comment]
I can't seem to duplicate it with a Swift class that inherits from NSObject 😔  I can rename the `User` object to something less commonly used but I would like to _actually_ know what the cause is first so its not just a yolo fix on my end 😇   I will keep trying to break things on my end

**Comment by carole-lavillonniere** [comment]
Seems like a more solid fix is required indeed, because I would assume the same could happen with common class names like `Event`, `Frame` or `Exception` etc (something worth testing maybe?).

**Comment by joshdholtz** [comment]
@carole-lavillonniere Everything should be namespaced out by the framework name which is why this issue was closed originally. Are you by any chance including the sentry framework twice? I'm trying to think of any project configurations could be different than what I have setup 🤔

**Comment by carole-lavillonniere** [comment]
The Sentry framework is only imported once and the compiler when failing points to the two different definitions: the one from Sentry and the one from my project.

Here is how I define my User class:
```
class User: NSObject {
   ...
}
```

**Comment by joshdholtz** [comment]
Very odd! I did that exact thing and no compile errors 😔  What version of Xcode/Swift?
Sorry for so many questions! Really want to get down to what is causing this 😇

**Comment by carole-lavillonniere** [comment]
Strange...
Xcode 7.3.1 and Swift 2.2

**Comment by carole-lavillonniere** [comment]
In your test app, is the `{YourAppName}-Swift.h` file generated?

**Comment by carole-lavillonniere** [comment]
In case it helps, I have just reproduced the error with the `Frame` class. No error if it does not inherit from `NSObject`, but the compilation fails with a `duplicate interface definition` when it does.

**Comment by joshdholtz** [comment]
@carole-lavillonniere I added a bridging header and still no failure 😖 

Here is what my view controller looks like which, based on the information you have provided, should fail (but its not)...

```swift
import UIKit
import SentrySwift

class User: NSObject {
	
}

class ViewController: UIViewController {

	override func viewDidLoad() {
		super.viewDidLoad()
		
		let user = User()
		print("user - \(user)")
		
		let client = SentryClient(dsnString: "")
		client?.startCrashHandler()
		
	}

}
```

Do you have a test/sample project that can reproduce this error by any chance?

**Comment by carole-lavillonniere** [comment]
Just to be sure we're talking about the same thing, I'm talking about the
header to expose swift to objective-c, and not the other way around.
I might be able to create a sample project, but not before Monday.

**Comment by joshdholtz** [comment]
@carole-lavillonniere Ohhhhh, thanks for that clarification! I will give that a shot... I forget that thats a thing sometimes 😉

**Comment by carole-lavillonniere** [comment]
I did not really need this header anymore, so I disabled its generation by deleting SWIFT_OBJC_INTERFACE_HEADER_NAME in the Xcode settings and it is now compiling.

**Comment by joshdholtz** [comment]
@carole-lavillonniere That is good to hear! I will still look into this but glad to hear that things are working for you now 😊

**Comment by carole-lavillonniere** [comment]
:) Thanks for the support!

**Comment by n1mda** [comment]
I have an Obj-C class called `User` in my project and it conflicts with Sentrys `User`.
How do I use my projects `User`? Since there's no namespace.

**Comment by HazAT** [comment]
@n1mda 
Hey we will add a namespace for objc in next minor bump because it breaks the current api.
For now you can only rename your `User` class or add SentrySwift as a project an namespace it by yourself like this.
http://softwaredesign.jeffverkoeyen.com/swift-frameworks-conflicting-symbols-objective-c-apps/

**Comment by HazAT** [comment]
@n1mda We just released `1.4.0` which namespaced all public classes in objc.
If you update your problem should be fixed.

**Comment by n1mda** [comment]
@HazAT Thank you, works great!

**Comment by leah** [comment]
Hey! I definitely have tried everything and cannot get this to work. I'm on SentrySwift 1.4.2 and Swift 3.

I have a User class in my project and I've tried `SentrySwift.User` ("Expression type User is ambiguous without more context") as well as `SentryUser` (not found at all). Any help?

Do I need to convert my whole class with the @objc prefix? That seems crazy.

**Comment by leah** [comment]
Quick update! I was able to get it to work with a typealias, thanks to a suggestion via email from @HazAT (thank you!).

My code now looks like:
```
import SentrySwift

typealias SentryUser = SentrySwift.User

SentryClient.shared?.user = SentryUser(id: id, email: email, username: slug, extra: [:])
```

Hope this is helpful for others.

**Comment by gustavoamgarten** [comment]
@leah 's solution didn't help me. I still can't make it work.

I have a swift class that imports Sentry, and that same class uses an User Objective-C class that I import in Bridging Header file. When I try to use the Objective-C User class I get the error:

`'User' is ambiguous for type lookup in this context`

The typelias didn't work.

Any suggestions?
